# Generated by Django 2.0.5 on 2018-05-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Contact',
        ),
    ]
