# Generated by Django 2.0.5 on 2018-05-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
